apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi

  bootstrap:
    initdb:
      database: pgbench
      owner: pgbench
      postInitApplicationSQL:
      - GRANT pg_checkpoint TO pgbench

